### ISSUE TITLE
Make a nodejs app

### ISSUE THREAD

**Issue by dyablohunter** [patrulek/rayscan#1]
Hi Patryk, found your repo in a reddit. Would you be willing to work with me and create a nodejs implementation of your rayscan?

**Comment by patrulek** [comment]
Im not a js developer, but if you have any question, im willing to answer.

**Comment by dyablohunter** [comment]
I can do the JS developing. I would love a video meet for a quick intro and to mix some ideas together: https://calendly.com/lucian-apetrei
Added you on LinkedIn as well. Lucian A.

**Comment by patrulek** [comment]
I prefer asynchronic communication via github. This way anyone who visit this repo may profit from this. If you have any question just ask, otherwise im closing this issue.

**Comment by dyablohunter** [comment]
Close it for sure. I would love to talk to you somewhere where we can have a conversation.

**Comment by patrulek** [comment]
Ok, so im closing it. If you have any specific question, just open new issue.
